### ISSUE TITLE
TypeScript error: Can't use image-logger middleware

### ISSUE THREAD

**Issue by chadstewart** [chadstewart/you-go-backend-project#1]
I made a logger middleware to log the requests and responses from the server. To get the response from the server, I'm adding a variable to the response object since Node/Express doesn't have a method to get access to a response that's already sent. To facilitate this, I created a interface that extends Response so that I can add the variable and TypeScript won't complain.

The interface is located here: [CustomResponse](https://github.com/chadstewart/you-go-backend-project/blob/main/nodejs/src/interfaces/custom-response.ts)

When I add CustomResponse to the image-logger middleware and try to use it in app, I get this error:
![Screenshot from 2022-04-17 13-48-06](https://user-images.githubusercontent.com/11777161/163728264-ca8055d7-3807-438b-a105-f0c49a1389a0.png)
![Screenshot from 2022-04-17 13-40-35](https://user-images.githubusercontent.com/11777161/163728241-37e6178f-f689-4c6d-8817-8c6632b03c72.png)

Any idea what I need to do here?

**Comment by jsjoeio** [comment]
@jsjoeio

**Comment by chadstewart** [comment]
> @jsjoeio

Guess you already tagged yourself to remind yourself.

**Comment by jsjoeio** [comment]
Did you fix it? When I use `customResponse` I don't see any errors?

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/3806031/164081528-ed77b9d5-3a01-4929-98ee-63ae5c03dd02.png">

**Comment by chadstewart** [comment]
> Did you fix it? When I use `customResponse` I don't see any errors?
> 
> <img alt="image" width="1904" src="https://user-images.githubusercontent.com/3806031/164081528-ed77b9d5-3a01-4929-98ee-63ae5c03dd02.png">

Oh no, I didn't fix it. It works fine if you try to use CustomResponse anywhere else in the app but if you specifically try to use it in the index.ts of logger, it'll cause app.ts to throw an error. At least it was like that a few days ago.

**Comment by jsjoeio** [comment]
Hmm...I might be missing something then. 

Can you push up branch that has the codebase in a state where it shows the error? Then I can check it out locally

**Comment by chadstewart** [comment]
> Hmm...I might be missing something then.
> 
> Can you push up branch that has the codebase in a state where it shows the error? Then I can check it out locally

@jsjoeio

I pushed up a branch with the error. Here is the branch: 

https://github.com/chadstewart/you-go-backend-project/tree/fix/logging-server-response

Let me know what you think.

**Comment by jsjoeio** [comment]
## How to reproduce:

1. clone repo
2. checkout branch `fix/logging-server-response``
3. open `app.ts`
4. see error on L38

Posting this since it would have been helpful to know this from the start fyi 

## Notes

Following [this example](https://typescript.tv/hands-on/how-to-type-express-js-middleware/), I think the issue lies in the use of `CustomResponse` for `res`. 

When you don't use that type, everything works as expected. But the problem is, when you give your middleware to `app`, TypeScript says, "hey this doesn't look right...I know what custom middleware is, but what you're giving me is custom middleware."

The part next that we need to figure out is, "How do we use a custom response with our Express app?"

Here's a link I found: https://www.kindacode.com/article/express-typescript-extending-request-and-response-objects/

another sidenote, if this middleware is only used for requests on `/image`, then you might be able to modify it to only use it on those routes.


Hmm...trying this and i'm seeing similar type errors 🤔 https://www.kindacode.com/article/express-typescript-extending-request-and-response-objects/

## How would I do this

I guess one thing for me to help you on this is  thinking "how would I approach this problem?" I'd break it down into mini-problems and solve those.

1. How to create custom middleware
2. How to create a custom response

Ideally we'd have tests set up so we could take a TDD approach.

And the middleware doesn't need to be in it's own function. I might start with [this approach](https://expressjs.com/en/guide/using-middleware.html#middleware.application) and then extract into a function if needed.


I just found this which might work as well. Then you don't need to create a custom Response. https://stackoverflow.com/a/65144765/3015595

**Comment by jsjoeio** [comment]
Seems like this approach might work?
```typescript
app.use("/image", (req, res, next) => {
  const { rawHeaders, httpVersion, method, body, url, params } = req
  const headers = res.getHeaders()
  const { statusCode, statusMessage } = res

  logger.info(
    JSON.stringify({
      rawHeaders,
      httpVersion,
      url,
      method,
      params,
      body,
    })
  )

  logger.info(
    JSON.stringify({
      headers,
      statusCode,
      statusMessage,
    })
  )

  res.locals.responseToUser = {
    name: "Chad",
    age: 30,
  }

  next()
})
```

**Comment by chadstewart** [comment]
> Seems like this approach might work?
> 
> ```ts
> app.use("/image", (req, res, next) => {
>   const { rawHeaders, httpVersion, method, body, url, params } = req
>   const headers = res.getHeaders()
>   const { statusCode, statusMessage } = res
> 
>   logger.info(
>     JSON.stringify({
>       rawHeaders,
>       httpVersion,
>       url,
>       method,
>       params,
>       body,
>     })
>   )
> 
>   logger.info(
>     JSON.stringify({
>       headers,
>       statusCode,
>       statusMessage,
>     })
>   )
> 
>   res.locals.responseToUser = {
>     name: "Chad",
>     age: 30,
>   }
> 
>   next()
> })
> ```

@jsjoeio

Thanks much, I'll check it out in a bit. Working the day job right now.

**Comment by chadstewart** [comment]
> Seems like this approach might work?
> 
> ```ts
> app.use("/image", (req, res, next) => {
>   const { rawHeaders, httpVersion, method, body, url, params } = req
>   const headers = res.getHeaders()
>   const { statusCode, statusMessage } = res
> 
>   logger.info(
>     JSON.stringify({
>       rawHeaders,
>       httpVersion,
>       url,
>       method,
>       params,
>       body,
>     })
>   )
> 
>   logger.info(
>     JSON.stringify({
>       headers,
>       statusCode,
>       statusMessage,
>     })
>   )
> 
>   res.locals.responseToUser = {
>     name: "Chad",
>     age: 30,
>   }
> 
>   next()
> })
> ```

@jsjoeio

Could you describe how this works? I'm not sure if this will work the way I want it to. If anything (and if you have time) we could hop on a call so I can give you a bit more context on what I was thinking.

**Comment by jsjoeio** [comment]
> Could you describe how this works? I'm not sure if this will work the way I want it to. If anything (and if you have time) we could hop on a call so I can give you a bit more context on what I was thinking.

It should work on any routes that have `/image` in them and log the info in your logger like you want. And then in the response, there will be a `.local` property with a property called `responseToUser`. Does that make sense?

Instead of hopping on a call, feel free to send me a [Loom](https://www.loom.com/) with more context if you think that'd be helpful.

**Comment by chadstewart** [comment]
> > Could you describe how this works? I'm not sure if this will work the way I want it to. If anything (and if you have time) we could hop on a call so I can give you a bit more context on what I was thinking.
> 
> It should work on any routes that have `/image` in them and log the info in your logger like you want. And then in the response, there will be a `.local` property with a property called `responseToUser`. Does that make sense?
> 
> Instead of hopping on a call, feel free to send me a [Loom](https://www.loom.com/) with more context if you think that'd be helpful.

Made a YouTube video talking about what I was thinking about. This is it:

https://www.youtube.com/watch?v=gSA1Sth-_rY

Let me know if this helps explain.

**Comment by chadstewart** [comment]
> > Could you describe how this works? I'm not sure if this will work the way I want it to. If anything (and if you have time) we could hop on a call so I can give you a bit more context on what I was thinking.
> 
> It should work on any routes that have `/image` in them and log the info in your logger like you want. And then in the response, there will be a `.local` property with a property called `responseToUser`. Does that make sense?
> 
> Instead of hopping on a call, feel free to send me a [Loom](https://www.loom.com/) with more context if you think that'd be helpful.

@jsjoeio

Made a YouTube video talking about what I was thinking about. This is it:

https://www.youtube.com/watch?v=gSA1Sth-_rY

Let me know if this helps explain.

**Comment by jsjoeio** [comment]
Hey Chad. Thanks for the video.

So yeah, I think it'd be helpful for you to take a look at the code I shared and maybe read the Express docs.

- [Express middleware](https://expressjs.com/en/guide/using-middleware.html#middleware.application)
- [res.locals](https://expressjs.com/en/api.html#res.locals)

This `app.use("/image"` says "use this middleware on any route with 'image' in the path". That eliminates the need to do this:
```typescript
    const isRequestToAnImageEndpoint = req.path.includes('/image');
```

because it will _only_ be run on requests which have 'image'. 

That way you can log to your `logger` the info you're looking for.

For the adding `responseToUser` to the response, you could do that in separate middleware for the `/blur` route. In the middleware, you can add it to `res.locals` like:

```typescript
  res.locals.responseToUser = {
    success: true,
    // anything else
  }
```

Does that all make sense?

**Comment by chadstewart** [comment]
@jsjoeio

Ohhh!!!! I see! Yeah, my bad. I did not read the docs on this at all, lol.

I tried it out and it worked the way I wanted. Thanks so much man! Much appreciated! I'm going to work on setting everything up and I'll push the changes!

**Comment by chadstewart** [comment]
> Hey Chad. Thanks for the video.
> 
> So yeah, I think it'd be helpful for you to take a look at the code I shared and maybe read the Express docs.
> 
> * [Express middleware](https://expressjs.com/en/guide/using-middleware.html#middleware.application)
> * [res.locals](https://expressjs.com/en/api.html#res.locals)
> 
> This `app.use("/image"` says "use this middleware on any route with 'image' in the path". That eliminates the need to do this:
> 
> ```ts
>     const isRequestToAnImageEndpoint = req.path.includes('/image');
> ```
> 
> because it will _only_ be run on requests which have 'image'.
> 
> That way you can log to your `logger` the info you're looking for.
> 
> For the adding `responseToUser` to the response, you could do that in separate middleware for the `/blur` route. In the middleware, you can add it to `res.locals` like:
> 
> ```ts
>   res.locals.responseToUser = {
>     success: true,
>     // anything else
>   }
> ```
> 
> Does that all make sense?


@jsjoeio

Ohhh!!!! I see! Yeah, my bad. I did not read the docs on this at all, lol.

I tried it out and it worked the way I wanted. Thanks so much man! Much appreciated! I'm going to work on setting everything up and I'll push the changes!

**Comment by jsjoeio** [comment]
LOL no worries at all - I had to re-read it a few times to understand what it meant. And your video helped me understand the `imageBlur` part.

Hooray!!! I'm so stoked to hear that. Go team :D 

Sweet!

**Comment by chadstewart** [comment]
> LOL no worries at all - I had to re-read it a few times to understand what it meant. And your video helped me understand the `imageBlur` part.
> 
> Hooray!!! I'm so stoked to hear that. Go team :D
> 
> Sweet!

Gonna make a pull request and reference this issue in it. I didn't add an extra middleware to the app yet but I plan to cause there's a bit of repeat code that I think I don't need to have.

Thanks so much for all the help! I wouldn't have come across this without you!

**Comment by jsjoeio** [comment]
> Thanks so much for all the help! I wouldn't have come across this without you!

I wouldn't have learned about `res.locals` without us doing this investigation together so thanks for helping me find that too. Go team!

**Comment by chadstewart** [comment]
> > Thanks so much for all the help! I wouldn't have come across this without you!
> 
> I wouldn't have learned about `res.locals` without us doing this investigation together so thanks for helping me find that too. Go team!

![0248d0a7-b06e-4f61-b549-00ffca732247_200_10](https://user-images.githubusercontent.com/11777161/165189584-0b23f562-10e9-483e-87c6-fa426fa07ba6.gif)
